In [7]:
import numpy as np

In [8]:
#Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim):
#a) Vector con enteros del 1 al 20.
#b) Matriz de ceros de 5 filas y 3 columnas.
#c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.
# a) Vector con enteros del 1 al 20
vector = np.arange(1, 21)
print('Vector:', vector)
print('shape:', vector.shape, 'dtype:', vector.dtype, 'ndim:', vector.ndim)

# b) Matriz de ceros 5x3
matriz_ceros = np.zeros((5, 3))
print('Ceros shape:', matriz_ceros.shape, 'dtype:', matriz_ceros.dtype)

# c) 10 puntos entre -1 y 1
puntos = np.linspace(-1, 1, 10)
print('Linspace:', puntos)
print('shape:', puntos.shape, 'dtype:', puntos.dtype)

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
shape: (20,) dtype: int64 ndim: 1
Ceros shape: (5, 3) dtype: float64
Linspace: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
shape: (10,) dtype: float64


In [9]:
#Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.
#Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].
np.random.seed(99)
matriz = np.random.randint(0, 51, size=(4, 4))
print(matriz)
print('shape:', matriz.shape)
print('dtype:', matriz.dtype)
print('nbytes:', matriz.nbytes)
print('elemento [2,3]:', matriz[2, 3])

[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
shape: (4, 4)
dtype: int64
nbytes: 128
elemento [2,3]: 49


In [10]:
#Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y
#np.array([1.0,2.0,3.0])? Verifica con código.
enteros = np.array([1, 2, 3])
flotantes = np.array([1.0, 2.0, 3.0])

print('Enteros dtype:', enteros.dtype)
print('Flotantes dtype:', flotantes.dtype)

Enteros dtype: int64
Flotantes dtype: float64


In [11]:
#Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal
#es igual a 5 (usa np.trace())
identidad = np.eye(5)
print(identidad)
print('Suma diagonal (trace):', np.trace(identidad))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Suma diagonal (trace): 5.0
