In [1]:
import numpy as np

In [3]:
#Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)
#a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.
#b) Extrae la segunda columna completa.
#c) Extrae los elementos de los ángulos (esquinas) de la matriz.
A = np.arange(1, 26).reshape(5, 5)
print(A)

# a) Sub-matriz: 3 ultimas filas, 3 primeras columnas
sub = A[-3:, :3]
print('Sub-matriz:\n', sub)

# b) Segunda columna completa
col2 = A[:, 1]
print('Segunda columna:', col2)

# c) Elementos de las esquinas
esquinas = A[[0, 0, -1, -1], [0, -1, 0, -1]]
print('Esquinas:', esquinas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sub-matriz:
 [[11 12 13]
 [16 17 18]
 [21 22 23]]
Segunda columna: [ 2  7 12 17 22]
Esquinas: [ 1  5 21 25]


In [4]:
#Ejercicio 2: Con la misma matriz A:
#a) Crea una máscara booleana para los valores mayores a 12.
#b) Reemplaza esos valores por -1 en una copia del array.
#c) Usa np.where para reemplazar impares por 0 y mantener los pares.
# a) Mascara para valores mayores a 12
mascara = A > 12
print('Mascara:\n', mascara)

# b) Reemplazar por -1 en copia
B = A.copy()
B[mascara] = -1
print('Copia con -1:\n', B)

# c) np.where: impares por 0, pares se mantienen
C = np.where(A % 2 == 1, 0, A)
print('Impares a 0:\n', C)

Mascara:
 [[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
Copia con -1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Impares a 0:
 [[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


In [6]:
#Ejercicio 3: Crea un vector de 24 elementos con arange(24).
#Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24.
#Taller de Python y NumPy | 6to Nivel | Google Colab Inteligencia Artificial
v = np.arange(24)
print('Original:', v.shape)

# a) Matriz 6x4
m64 = v.reshape(6, 4)
print('6x4:', m64.shape)

# b) Tensor 2x3x4
t234 = v.reshape(2, 3, 4)
print('2x3x4:', t234.shape)

# c) Vector fila 1x24
fila = v.reshape(1, 24)
print('1x24:', fila.shape)

Original: (24,)
6x4: (6, 4)
2x3x4: (2, 3, 4)
1x24: (1, 24)


In [7]:
#Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento
#en un slice y verifica que el array original también cambia.
arr = np.arange(10)
print('Original:', arr)

# Slice es vista
vista = arr[2:5]
vista[0] = 999
print('Desde modificada:', arr)
print('El original tambien cambio porque el slice es una vista')


Original: [0 1 2 3 4 5 6 7 8 9]
Desde modificada: [  0   1 999   3   4   5   6   7   8   9]
El original tambien cambio porque el slice es una vista
