In [3]:
import numpy as np

In [4]:
#Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).
#a) Calcula la media, máximo y mínimo de cada columna.
#b) Calcula la suma acumulada de la primera fila.
#c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
#Fórmula: (x - min_col) / (max_col - min_col)
np.random.seed(7)
M = np.random.randint(1, 101, size=(5, 4))
print(M)

# a) Media, max, min por columna
print('Media columnas:', M.mean(axis=0))
print('Max columnas:', M.max(axis=0))
print('Min columnas:', M.min(axis=0))

# b) Suma acumulada primera fila
print('Suma acumulada fila 0:', np.cumsum(M[0]))

# c) Normalizar columnas entre 0 y 1
min_col = M.min(axis=0)
max_col = M.max(axis=0)
normalizada = (M - min_col) / (max_col - min_col)
print('Normalizada:\n', normalizada)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]
Media columnas: [51.8 51.4 41.8 60.2]
Max columnas: [84 91 93 90]
Min columnas: [15 24  8 40]
Suma acumulada fila 0: [ 48 117 143 211]
Normalizada:
 [[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


In [5]:
#Ejercicio 2: Usando broadcasting:
#a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].
#b) Suma ambos vectores y explica el shape del resultado.
# a) Vector fila y vector columna
fila = np.array([1, 2, 3, 4])
columna = np.array([[10], [20], [30]])

print('Fila shape:', fila.shape)
print('Columna shape:', columna.shape)

# b) Suma
resultado = columna + fila
print('Resultado:\n', resultado)
print('Resultado shape:', resultado.shape)
print('El shape es 3x4: se expande la fila a 3 filas y la columna a 4 columnas')

Fila shape: (4,)
Columna shape: (3, 1)
Resultado:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Resultado shape: (3, 4)
El shape es 3x4: se expande la fila a 3 filas y la columna a 4 columnas


In [6]:
#Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:
#a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)
#b) Imprime solo los nombres de esos estudiantes.
#Taller de Python y NumPy | 6to Nivel | Google Colab Inteligencia Artificial
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])

# a) Cuantos tienen nota mayor al promedio
promedio = notas.mean()
mayores_promedio = notas > promedio
cantidad = np.sum(mayores_promedio)
print('Promedio:', promedio)
print('Cantidad mayor al promedio:', cantidad)

# b) Nombres de esos estudiantes
print('Nombres:', nombres[mayores_promedio])

Promedio: 81.5
Cantidad mayor al promedio: 3
Nombres: ['Ana' 'Diana' 'Eva']


In [7]:
#Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.
#Luego divide el resultado vertical en 3 partes iguales con vsplit.
A = np.arange(12).reshape(3, 4)
B = np.arange(12, 24).reshape(3, 4)

# Concatenar vertical
vertical = np.vstack((A, B))
print('Vertical 6x4:\n', vertical)

# Concatenar horizontal
horizontal = np.hstack((A, B))
print('Horizontal 3x8:\n', horizontal)

# Dividir vertical en 3 partes
partes = np.vsplit(vertical, 3)
print('Partes:', len(partes))
for i, p in enumerate(partes):
    print(f'Parte {i} shape:', p.shape)

Vertical 6x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Horizontal 3x8:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
Partes: 3
Parte 0 shape: (2, 4)
Parte 1 shape: (2, 4)
Parte 2 shape: (2, 4)
